dist: trusty
language: java
sudo: false
install: true

addons:
  sonarqube:
    organization: "arxes-tolina"
    token:
      secure: "Ja+klUuZ2M0ODpfbnHKt3QBLmz6UwWDmDgVMFn8NVNhYrg5tydU0NTYfTaIAlysXt5jLgQHy78jOZhcHlWrS6sEy4tRZKvkFce/BxND9/ulO5+9tqy4vYKbcY90HrT/BAdMJyXZ+DoZKT9DvCNN7jxtOrvK9OaNIiWm+goeaevRtkALCUqkGwM/hCdbHdVrv//VrLxj5WjFclWJAdvBU3TTaxE3pvTvogPSYtIJUvHo/qcKA1U7eoU/6KMq7+CVJZHff0KMth+tqB8SNhv8eCQDVfneRjtCEmUoCDDMmtBf4uc/uc0AtdTCYW3KyfyjrsOFrGm2/JxGkJ334vcQFHyPUwSnICyD+xqZbiSgi76UmA6CjYiEn+4/jyvoE0kQV0h3uYhAxxj8ShfXh88Jeh1DXL9S1Oe2W0gRhLms2winz2uz+zvEpGBfy9Q2mzwd7gWoofxfI0AnB2d0rb9IR7l88GspN8N4dvHk8aB552jRMTngCqsH8u14ab2bnJPfl1XEZmED/TxlwGOCdHCC3qLcDmc+B7t2k7V2HUjwjeQ+vEfs6aQkWYJY2ujSJmujpgxOebIC4TuvHpiuyR4kuzYGc1RJC4s7UfpJ9u5rwfmsT+l1X/AwauyW7lRPDuqainIokDEJaAh+Oi4cipI5Q4mKMfd1m/NK/cKyWsG2j/Hg="

jdk:
  - oraclejdk8
  - oraclejdk11

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean verify sonar:sonar -Pcoverage-per-test

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
