dist: trusty
language: java
sudo: false
install: true

addons:
  sonarqube:
    organization: "fjakop-github"

jdk:
  - oraclejdk8
  - oraclejdk11

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean verify sonar:sonar -Pcoverage-per-test

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
